name: Build and Test

on:
  workflow_call:
    inputs:
      qc-max-success:
        description: 'Maximum number of successful tests for QuickCheck'
        required: false
        type: number
        default: 10000

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  check-cabal:
    uses: nikita-volkov/haskell-hackage-lib-github-actions-workflows/.github/workflows/check-cabal.yaml@v4
    secrets: inherit

  build-with-ghc-8-8:
    uses: nikita-volkov/haskell-hackage-lib-github-actions-workflows/.github/workflows/build.yaml@v4
    secrets: inherit
    with:
      ghc: "8.8"
      skip-doctest: true
      skip-benchmarks: true
      test-options: >
        --qc-max-success=${{ inputs.qc-max-success }}
  
  build-with-latest:
    uses: nikita-volkov/haskell-hackage-lib-github-actions-workflows/.github/workflows/build.yaml@v4
    secrets: inherit
    with:
      skip-doctest: true
      test-options: >
        --qc-max-success=${{ inputs.qc-max-success }}
